name: "Trufflehog"
description: "Analyse Repository finding exposed"
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  githubToken:
    description: 'GitHub Token to access a private repository.'
    required: false
  scanArguments:
    description: 'Argument options for scan.'
    required: false
branding:
  icon: 'shield'
  color: 'yellow'