name: GitHub Actions Demo
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: trufflehog-actions-scan
        uses: ./.github/actions/trufflehog
        with:
          scanArguments: "--regex --entropy=False --max_depth=5"