name: GitHub Actions Demo
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - dev
      - releases
      - feature/*
      - bugfix/*
      - fix/*
      - releae/*
      
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
          includePrerelease: true

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
